### ISSUE TITLE
Support obtain/put

### ISSUE THREAD

**Issue by alexsimply** [rickhowe/diffchar.vim#10]
While vim's diff is vastly improved with hightlighting at unit level - the vimdiff obtain (`do`) and put (`dp`) still operate on a line diff basis - but replacing based on the currently highlighted unit would greatly improve functionality

![Example replace](https://i.imgur.com/CFUuqex.gif)

**Comment by rickhowe** [comment]
Thank you for your idea and let me try to implement it in my plugin. Maybe 'Do' and 'Dp' commands over a difference unit can be added.

**Comment by alexsimply** [comment]
Great, thanks for the consideration!

**Comment by rickhowe** [comment]
I updated to 7.0 and added unit-based do/dp, <Leader>g and <Leader>p. You can change the keymap for them, and combine them with ]b or [b if necessary. Please try.

**Comment by alexsimply** [comment]
Having tested this it works perfectly for my use case 👍 

Many thanks rickhowe - awesome!
