### ISSUE TITLE
Change syntax text colour to differ from highlighting colour

### ISSUE THREAD

**Issue by protist** [rickhowe/diffchar.vim#12]
I just updated to 7.31 (and briefly 7.3 before that), and I noticed that the highlighting colours have changed. Now the changes are highlighted with a red background. However, when the text is red because of syntax highlighting, it is unreadable.

![red on red](https://i.imgur.com/H8yAKV2.png)

I'm not sure if this issue is something new, or it's just that I've noticed it now. Is there a way to automatically change the text colour when it is identical to the background colour?

**Comment by rickhowe** [comment]
Thank you for your interest. Probably the reason is a colorscheme you are using. not the plugin. In your example, the colors look silimar between your text's foreground and DiffText background. Please try :%RDChar (reset dchar) so that you can check how vim originally colors them.

**Comment by protist** [comment]
Thanks for the quick reply. That command did nothing at all.

Yes, I presume that the red foreground colour of my text is due to the syntax colour scheme, which has nothing to do with diffchar. However, I was wondering if diffchar could override the text's foreground colour when it changes the background highlighting scheme.

**Comment by rickhowe** [comment]
Your example has only one difference in a line. so %RDChar looks do nothing. You could check it if a line has two or more parts of differences.

Yes, diffchar always try to override the text with DiffText color but vim keeps the forground to make them look the same even if in the diff mode. For example, your 2nd line (pkgver=7.?) has a few forgrounds and vim keeps them also in the diff mode.

**Comment by protist** [comment]
Ah right, I think I understand now. So `:%RDChar` essentially "resets" the highlighting to the default vim settings.

With a bit more investigation, I found my problems relate to a line in `~/.vimrc`. Previously, I had found the default colours to be a bit hard to read, so I had set the following, as per [this tip](https://stackoverflow.com/a/13370967):
```
highlight! link DiffText MatchParen
```
This line worked with diffchar 7.2, but doesn't work in 7.31.

FWIW instead of this syntax, I can use something like the following format, which works instead.
```
highlight DiffAdd    cterm=bold ctermfg=10 ctermbg=17 gui=none guifg=bg guibg=Red
highlight DiffDelete cterm=bold ctermfg=10 ctermbg=17 gui=none guifg=bg guibg=Red
highlight DiffChange cterm=bold ctermfg=10 ctermbg=17 gui=none guifg=bg guibg=Red
highlight DiffText   cterm=bold ctermfg=10 ctermbg=88 gui=none guifg=bg guibg=Red
```

**Comment by rickhowe** [comment]
Hi. I checked again and found that 7.31 did not allow to change highlights while diff mode for both vim and neovim. I just updated it to 7.32 as similar to 7.2 for vim. However, if you are using nvim 2.1 or later, the limitation is still there.

**Comment by protist** [comment]
Fantastic! That works well. (I'm using vim.) Thank you for the quick fix!
