### ISSUE TITLE
Work on a single file containing diff output?

### ISSUE THREAD

**Issue by iology** [rickhowe/diffchar.vim#14]
I want to highlight the word/char-diff inside each section of the diff output. Could you provide a special mode or function for this purpose? It doesn't have to update the highlight.

At the same time, I'm modifying [dwdiff](https://os.ghalkes.nl/dwdiff.html) for the same effect (only for unified context, not copied context). But a pure vimscript solution would be great too!

**Comment by rickhowe** [comment]
If you want to compare different 2 sections in a single file, such as diff output, my another plugin
https://github.com/rickhowe/spotdiff.vim
might be useful. Please let me know if that would not help you.

**Comment by rickhowe** [comment]
If you want to compare different 2 sections in a single file, such as diff output, my another plugin
https://github.com/rickhowe/spotdiff.vim
might be useful. Please let me know if that would not help you.

**Comment by iology** [comment]
No, that plugin also makes use of `diffthis` and needs two window. I want to edit the diff output in place with the help from the highlight, then simply save and apply the patch.

I forgot to mention the expected output format.

e.g. original diff section

```diff
-A bad day.
+A good day.
```

e.g. modified (deletion and insertion on separate lines)

```diff
-A [-bad-] day.
+A {+good+} day.
```

then after my edit it becomes

```diff
-A [-bad-] day.
+A {+nice+} day.
```

finally, when the file is saved the concealed tags should get removed.

**Comment by rickhowe** [comment]
Both my plugins are intended to make vim's diff mode more useful.
If you would need something other than the diff mode in vim, 
those plugins can not be enhanced to meet your needs.

**Comment by iology** [comment]
No problem. I can try to implement it myself. I was interested by that auto-update after modification and wondered if those functions can be easily reused for implementing this new feature. 😃

**Comment by rickhowe** [comment]
This is just FYI but I made a simple vim script which might be useful for you.
Steps are described in the file. Please try it if necessary.
[dout_diff.zip](https://github.com/rickhowe/diffchar.vim/files/2562276/dout_diff.zip)

**Comment by iology** [comment]
Clever solution! I feel so meta now.

I customized it a bit so it can mark the change in the original file. The only downside is that vim slows down a lot, even if the texts are trimmed down to 2000 lines (no empty lines).

Here is the new script:

```vim
" Steps
" 1. open a diff output file
" 2. execute this script (:so dout_diff.vim)
"    - appear a dummy window on right side
"    - show the file and change '-' lines with correspponding '+' lines
"    - show the file and change '+' lines with correspponding '-' lines
"    - do diffthis on both windows
" 3. edit the file as required and save it
" 4. do diffoff!
" 5. quit the dummy window

let lines = getline(1, 2)
if lines[0][0] == '-' && lines[1][0] == '+'				" unified format
    let changes = []
    let i = 3
    let n = line('$')
    while i <= n
		let line = getline(i)
		if line[0] == '+'
			if !empty(changes)
                let m = i + len(changes)
                for j in range(i, n)
                    let line = getline(j)
                    if line[0] == '+'
                        if j < m
                            let lines += ['-' . line[1:]]
                        else
                            let lines += ['-']
                        end
                        let i = j
                    else
                        break
                    endif
                endfor
				let lines += changes
				let changes = []
            else
                let lines += [line]
			endif
		elseif line[0] == '-'
            let changes += ['+' . line[1:]]
        else "if line[0] == ' ' || line[0] == '@'
            let changes = []
            let lines += [line]
        endif
        let i += 1
    endwhile
endif

if !empty(lines)
    let wid = bufwinid('%')

    aboveleft 1new
    call setline(1, lines)
    let &l:modifiable = 0
    let &l:buftype = 'nofile'
    let &l:bufhidden = 'wipe'
    let &l:buflisted = 0
    let &l:swapfile = 0
    diffthis

    call win_gotoid(wid)
    diffthis
endif

" vim: ts=4 sw=4
```
