### ISSUE TITLE
Readme is missing <Leader> prefix when explaining get/put semantics of diffchar

### ISSUE THREAD

**Issue by spidey** [rickhowe/diffchar.vim#16]
Maybe GitHub filtered it because of the angle brackets. But even though the default are `<Leader>g` and `<Leader>p`, the readme as rendered on the front page of the repository states it's only `g` and `p` directly.

Also, why not using `<Leader>o`, like `do` from vimdiff? Any specific reason? I know I can change it easily.

**Comment by rickhowe** [comment]
Thank you I noticed now. I will revise soon. I just followed `:diffget` for `<Leader>g`.

**Comment by rickhowe** [comment]
It is reviced in 8.5.
