### ISSUE TITLE
3 diffs causes a crash

### ISSUE THREAD

**Issue by Rich-YoYo** [rickhowe/diffchar.vim#17]
DiffChar gets very confused and crashes with 3 diff windows. To reproduce;-

Create three files, a, b c. I'll describe the contents I used in case the number of lines is relevant to the problem

a : 5 lines of text, 1 character per line
b : 11 lines of text, 1 character per line
c: 8 lines of text, 1 character per line

- Load each file so that a is in buffer 1, b in buffer 2 and c in buffer 3 (all three files displayed)
- Enable diff mode for each buffer in-turn
- Go to buffer 2 (b), visually select line 4 (say) and then...

  :'<,'>diffget 1              [this should copy from buffer 1 (a)) to buffer 2 (b)]

In version 8.2, the error tended to be reported from UpdateDiffChar(), line 52 on the lines of...

  E684: List index out of range: 5

In version 8.3, the error tends to be on the lines of...

  Error detected while processing function <SNR>40_UpdateDiffChar[82]..diffchar#ShowDiffChar[9]..<SNR>40_GetDiffModeLines:
  line    3:
  E684: List index out of range: 5

...though the difference could be down to the exact sequence I used. I'm not sure.
The details also vary depending on how many times I've tried this (undoing and the re-trying the 'diffget').
The errors also cascade into other functions sometimes

...etc...

**Comment by rickhowe** [comment]
Thank you . I can reproduce the problem. To prevent confusion, in the next version, I will change to reset the DiffChar if there are more than 2 diff mode buffers when updated.

**Comment by rickhowe** [comment]
I have updated diffchar to 8.4. to fix it. Please try.

**Comment by Rich-YoYo** [comment]
Preliminary use seems to be ok. I'll let you know over the coming days/weeks
