### ISSUE TITLE
No diffchar highlight with vimdiff as git mergetool

### ISSUE THREAD

**Issue by ptzz** [rickhowe/diffchar.vim#19]
With `diffchar.vim` installed and using `vimdiff2` as git mergetool, the highlighting is the same as without `diffchar.vim` installed. I.e. no word level diff highlighting.

If I disable diff (`:diffoff`) for the merge buffer, so that only two buffers have diff enabled, word highlighting works fine.

Does `diffchar` only work when there are exactly two buffers with diff enabled?

**Comment by rickhowe** [comment]
Yes, to prevent any trouble, diffchar 8.4 works only on two diff mode windows in a tab page.
As a git mergetool, 
https://github.com/whiteinge/diffconflicts
has two-way diff in a tab page and it might be suitable with diffchar.
