### ISSUE TITLE
Allow arbitrary regexps in DiffUnit

### ISSUE THREAD

**Issue by Coacher** [rickhowe/diffchar.vim#2]
Hello.

Currently DiffUnit value can only be one of the predefined regexps. While it's good to have sensible defaults it would be nice to be able to use custom ones as well.

Please add this feature.

**Comment by rickhowe** [comment]
Thanks for asking. Actually there is an internal, my test purpose only, value for DiffUnit, which is SRE(). For example,

> let t:DiffUnit = 'SRE(\%(.\{,3}\)\zs)'

will define a block of 3 characters (maximum) as a difference unit.
You can use split() function with this regexp to see if they are correctly splitted.

**Comment by Coacher** [comment]
I see. This solves the problem for me.
I should've looked in sources, but I only checked docs.
Thank you.
