### ISSUE TITLE
Feature request: Make current highlighting also visable for the built-in function :TOhtml

### ISSUE THREAD

**Issue by dantasan** [rickhowe/diffchar.vim#24]
When I'm executing the :TOhtml command I don't get the currently with diffchar made highlightning, I just get the default highlightning from the vimdiff command. It would be great if the diffchar status could be also "captured" with the Tohtml command.
Thanks a lot in advance.

**Comment by rickhowe** [comment]
Thanks for your request. I  remembered that I had developed the sample plugin to support this. Please download rickhowe/sample/diffcharTOhtml.vim and load it on vim using :source or :runtime command. You can use the same :TOhtml command.

I would recommend to do `let g:DiffFocalPages=0` in advance to invoke diffchar plugin to check all lines (as a default, it dynamically checks just 3 pages on display for performance reason).

**Comment by dantasan** [comment]
Thanks a lot for your really fast response, I tried it out but I'm sorry to say that it didn't worked.

**Comment by dantasan** [comment]
Hi once again,
now I had a little bit more time and checked it again and also updated to the newest version of diffchar and it works perfectly!
Thanks a lot once more for your really fast answer!
This plugin is really cool!
All the best from Austria!
