### ISSUE TITLE
Recursive diff with diffchar supported

### ISSUE THREAD

**Issue by qpkorr** [rickhowe/diffchar.vim#28]
Hi,

First up - THANK YOU! I love vimdiff but the lack of this feature was a major issue to me, pushing me to meld or something similar.
So I was super pleased to find one tiny comment on StackOverflow about your plugin - it's awesome, thanks so much!

One question - meld is also decent for comparing two directories with matching files - but for that task I prefer to use dirdiff, from here:
https://github.com/will133/vim-dirdiff  
But having installed your plugin, it works great when I launch it on just two files, but when I run dirdiff to diff two directories, and then the files within them, your plugin appears not to activate.  I've tried adding a little debugging - and it seemed like it wasn't being called at all when dirdiff first opened (or exiting quickly?), and when changing files, it is getting called, but it's messing up dirdiff windows.

If you have a better solution for diffing two directories with (largely) matching filenames - that works with diffchar - I'll happily change - else - any chance of getting diffchar to work with dirdiff, or giving me some tips to help achieve that?

Thanks again,
John

**Comment by rickhowe** [comment]
Thank for using the plugin and asking the question. I am a beginner of the DirDiff plugin but looks work fine as below. 

![demo](https://user-images.githubusercontent.com/3096934/153230360-fa813293-ac24-4731-b01e-642cafc3ff13.gif)

Please let me know details of your problem.

I am using the latest 8.91 diffchar on gvim 8.2 in Windows 10.

**Comment by qpkorr** [comment]
Thanks very much for the prompt reply - it must be some other plugin I'm using that's screwing things up.  I'll investigate further.

**Comment by qpkorr** [comment]
Ah - turns out I was suffering from this bug in DirDiff https://github.com/will133/vim-dirdiff/issues/27 - I thought I'd updated all my plugins yesterday but it seems I missed DirDiff.  Seems to be working well thank you! Sorry for wasting your time!
