### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by protist** [rickhowe/diffchar.vim#3]
Hello, did you want to add a licence for your project? I'm packaging it for Arch Linux's AUR, and just wanted to make sure it's released properly. Cheers.

**Comment by protist** [comment]
So I guess that's a no?

Thanks for the great software and frequent updates anyway!

**Comment by rickhowe** [comment]
Sorry for my late reply and thanks for using.
I have added a license term in all files since 8.0 release.
Yes, that is 100% my own plugin.

**Comment by protist** [comment]
@rickhowe No worries; it's a great add-on for vim!

> I have added a license term in all files since 8.0 release.

Do you mean the copyright line? I was actually talking about the type of licence itself, e.g. GPL, MIT, etc. It's not essential, but it makes clear what the terms of distribution are, e.g. can others distribute with no restriction, do they have to use the same licence, can they commercialise it?
