### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by a2nath** [rickhowe/diffchar.vim#36]
Hello, is there a step-by-step installation instructions somewhere? 
I did a clone inside the ~/.vim dir and renamed the new dir from diffchar.vim to diffchar

Then I added the "let g:DiffExpr = 1" at the end of the ~/.vimrc 
I don't see the word by word diff. And even tried hitting F7 couple of times.

**Comment by rickhowe** [comment]
Hi,
There is no specific procedure for diffchar.vim. You should be able to install it as same as other plugins. In your case, it would be necessary to add 'set rtp+=~/.vim/diffchar.vim' in your ~/.vimrc. (no need to change dir name). Note that 'g:DiffExpr' and 'F7' are not available in recent versions.

**Comment by a2nath** [comment]
I resolved this issue just after posting this question, by creating the directories, ./vim/path/vendor/start and there I cloned the repo. Changed the name from diffchar.vim to diffchar directory. I'm not sure what the difference is from the solution above ^ but it works now
