### ISSUE TITLE
vimdiff whole line is green/red and colours don't show

### ISSUE THREAD

**Issue by HaleTom** [rickhowe/diffchar.vim#4]
I have:
`let g:DiffColors = 1 " 4 colours`

But this is what I see:
http://i.imgur.com/PNeI1Bv.png

How do I get the colours to show?

**Comment by rickhowe** [comment]
Thank you for asking. Please try
`echo t:DChar.dmc`
and see if
`['DiffText', 'NonText', 'Search', 'VisualNOS']`
is displayed. Those are the highlight groups used for this setting in this order.
Please check your 'DiffText' and 'NonText' and if both look mostly same.
If looks different, I would like to reproduce your example here to check in details.

**Comment by rickhowe** [comment]
Thank you for asking. Please try
` echo t:DChar.dmc`
and see if
` ['DiffText', 'NonText', 'Search', 'VisualNOS'] `
 is displayed. Those are the highlight groups used for this setting in this order.
 Please check your 'DiffText' and 'NonText' and if both look mostly same.
 If looks different, I would like to reproduce your example here to check in details.

**Comment by HaleTom** [comment]
My output is:
`['DiffText']`, but only after pushing `F7` in diff mode.

I have no hightlighting for `DiffText` defined.

When running `vi` at the prompt, then typing `:echo t:DChar.dmc`
```
E121: Undefined variable: t:DChar                                                                                                                                                                      
E15: Invalid expression: t:DChar.dmc                                                                                                                                                                   
Press ENTER or type command to continue
```

My entire config relating to diffchar is:
```
" diffchar
let g:DiffColors = 1 " 4 colours
```

Where to from here?

**Comment by rickhowe** [comment]
I found my typo error since 6.0. I will fix it at the next update. Meanwhile, please set a tabpage variable instead of the global one as a workaround in your vimrc like this:
`let t:DiffColors = 1 `

**Comment by HaleTom** [comment]
Works fine - thanks. I'll wait for your closing this as a sign I can remove that line.

**Comment by rickhowe** [comment]
Hi, I updated the plugin to 6.3 and fixed this problem. Please try. Thank you.
