### ISSUE TITLE
[Regression] Visual mode broken

### ISSUE THREAD

**Issue by protist** [rickhowe/diffchar.vim#5]
I just upgraded to diffchar 6.3, and visual mode no longer works. I press `v` or `V`, then attempt to move with `hjkl`. Vim immediately puts me back in normal mode.

I tried reverting to diffchar 6.2, and visual mode works perfectly. Visual mode is obviously important for `:diffget`, etc.

**Comment by rickhowe** [comment]
Thanks for using and asking. I found my error. Please try to add one line in autoload/diffchar.vim as a workaround. I will check any other regression in visual mode.

```
--- diffchar.vim	2016-10-12 13:56:06.353957400 +0900
+++ diffchar2.vim	2016-10-13 19:35:23.315363200 +0900
@@ -993,6 +993,8 @@
 endfunction
 
 function! s:ShowDiffCharPair(key)
+	if mode() != 'n' | return | endif
+
 	call s:RefreshDiffCharWID()
 
 	let bkey = (a:key == 1) ? 2 : 1
```

**Comment by protist** [comment]
Thank you. That works perfectly! (Also I do very much like the improvements to 6.3. The dynamic highlighting of the other pane is very cool!)

**Comment by Coacher** [comment]
I also experience this problem. I can provide any extra info if needed.

**Comment by protist** [comment]
Fixed in release.
