### ISSUE TITLE
diffupdate command doesn't work with diffchar>=6.8

### ISSUE THREAD

**Issue by Coacher** [rickhowe/diffchar.vim#8]
Hello.

When I run diffupdate lines that were different, but now are the same, keep their highlighting of previously different parts and aren't moved under fold. Didn't happen with diffchar<6.8.

**Comment by rickhowe** [comment]
Thank you. It is a regression. In 6.8, I changed the way to detect diff mode by OptionSet event,
but I noticed this way did not detect  :diffupdate (and :set diffopt).
I think I would need to recover back to 6.7.
As a workaround, find several lines including "has('patch-8.0.736')" in diffchar.vim in both plugin and
autoload directories and replace it to "has('patch-8.0.000')" .
